### ISSUE TITLE
Error with DirectionsService

### ISSUE THREAD

**Issue by bpillon** [a14n/dart-google-maps#105]
Hello ! 

First of all, thank you for your awesome lib.

I have a strange error when I try to request a directions with waypoints : 

```
Expected a value of type 'JSObject<undefined>', but got one of type 'String'
    at Object.throw_ [as throw] (http://localhost:54427/dart_sdk.js:5348:11)
    at Object.castError (http://localhost:54427/dart_sdk.js:5319:15)
    at Object.cast [as as] (http://localhost:54427/dart_sdk.js:5635:17)
    at dart.LegacyType.new.as (http://localhost:54427/dart_sdk.js:7233:60)
    at Object._argumentErrors (http://localhost:54427/dart_sdk.js:5471:19)
    at Object._checkAndCall (http://localhost:54427/dart_sdk.js:5554:29)
    at Object.dcall (http://localhost:54427/dart_sdk.js:5563:17)
 at ret (http://localhost:54427/dart_sdk.js:61423:21)
    at https://maps.googleapis.com/maps-api-v3/api/js/45/8b/intl/fr_ALL/directions.js:140:493
    at https://maps.googleapis.com/maps-api-v3/api/js/45/8b/intl/fr_ALL/directions.js:9:7
    at Gha.j (https://maps.googleapis.com/maps-api-v3/api/js/45/8b/intl/fr_ALL/directions.js:4:478)
    at Object.c [as _7sm72k] (https://maps.googleapis.com/maps-api-v3/api/js/45/8b/intl/fr_ALL/common.js:107:253)
    at https://maps.googleapis.com/maps/api/js/DirectionsService.Route?5m4&1m3&1m2&1d48.99433373&2d2.65064746&5m4&1m3&1m2&1d48.8902034&2d2.3730494&5m4&1m3&1m2&1d48.9448404&2d2.2396764&5m4&1m3&1m2&1d48.8237958&2d2.4098053&5m4&1m3&1m2&1d48.99433373&2d2.65064746&6e0&12sfr-FR&23e1&callback=_xdc_._7sm72k&key=MY_TOKEN&token=108873:1:28
````

When I call the URL at the bottom (with my token), the response is a 200 and seems correct, so my request is ok too, I guess.
I have already used the DirectionsService by the past and it worked with no problem. Do you have any idea to help me ? 

Thanks !

**Comment by a14n** [comment]
Thanks for the report.

Fixed by 27e09e79f8ad80c86bb3f2dc1f21d98073ef53ca and available in 5.3.0
